### PR TITLE
[Fix] [iOS] Ensure that custom URL scheme URLs are parsed correctly

### PR DESCRIPTION
**Pull request by chrisweight**
I found that the plugin was not parsing custom url scheme URLs correctly prior to sending them on to a consuming app, this PR addresses that issue, so now both universal links and custom url scheme links are handled consistently.

Also cleans up some of the code.

### CODE REVIEW

**Comment by chrisweight** [comment]
@cwoolum - Any chance this could be reviewed / merged+released-if-happy at all please?

Cheers!

**Review by cwoolum — APPROVED** [review]
Looks good! Will push out a release today!

**Comment by cwoolum** [comment]
Released as version `0.2.3`

**Comment by chrisweight** [comment]
Cheers @cwoolum - I might drop another PR in that deals with the matchType as well, as that'd be useful for links sharing more personal / sensitive information

**Pull request merged**
